export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const GET_INITIAL_FLIGHTS = 'GET_INITIAL_FLIGHTS';
export const CHANGE_TIME = 'CHANGE_TIME';
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const STOP_LOADING = 'STOP_LOADING'